# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff3120aacff390b649a405f608ec7cc7bc5c38fa89842a1719cbb09c2a3d074f880731d120889aad6824420859070d4d15e8ff11d7644bc37f3e8f9268f810a8

test:
  secret_key_base: 5ba50baf2785f9917216ffe481f70a7829b84a6a379a5769e2714edccaf4d51c1de7a1890654f57892ffedb83047accc8af034fa204a45d84500c0696dde929f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
